---

- hosts: localhost
  connection: local
  user: root
  pre_tasks:
    - include_vars: variables.yml

- hosts: 54.90.245.228
  connection: ssh
  vars:
    ansible_python_interpreter: /usr/bin/python3
  user: ubuntu
  pre_tasks:
    - include_vars: variables.yml
  tasks:
    - name: Make temp dir
      shell: "mkdir -p {{ artifact_dest }}"
